### PR TITLE
Accept any minor (backwards compatible) changes to d2l-icons.

### PR DESCRIPTION
**Pull request by njostonehouse**

### CODE REVIEW

**Comment by dbatiste** [comment]
Looks good to me.  I would imagine we could bump to 2.5 while we're at it?

**Comment by njostonehouse** [comment]
@dbatiste Bumped to 2.5. I can't merge this one; I don't have permission.

**Comment by dlockhart** [comment]
Looks like there are conflicts that need resolvin' first

**Comment by dlockhart** [comment]
@njostonehouse you also have write access now

**Pull request merged**
